SRCS:=\
	mpool_fixed_ut.cpp mpool_variable_ut.cpp malloc_ut.cpp class_new_delete_ut.cpp \
	mpool_allocator_ut.cpp global_new_delete.cpp global_new_delete_ut.cpp \
	exception_allocator_ut.cpp pmr_memory_resource_ut.cpp pool_resource_ut.cpp

CPP_VER:=c++17
SHARED:=../../essential/
include $(SHARED)make/env.mk
include $(SHARED)make/example.mk
include $(SHARED)make/gtest.mk
