SRCS:=\
    parameter_pack_ut.cpp nstd_type2str_ut.cpp nstd_float_ut.cpp logger_0.cpp logger_0_ut.cpp \
    logger_0_std_ut.cpp logger_0_global_ut.cpp logger_0_logging_ut.cpp logger_0_struct_ut.cpp \
    logger_0_no_put_to_ut.cpp nstd_0_ut.cpp safe_vector_ut.cpp type_traits_ut.cpp \
    is_void_ut.cpp is_same_ut.cpp nstd_type_traits_ut.cpp exists_func_ut.cpp value_type_ut.cpp \
    nstd_safe_index_ut.cpp safe_index_put_to_ut.cpp nstd_put_to_ut.cpp \
    logger_ut.cpp universal_ref_ut.cpp generic_lambda_ut.cpp suppress_adl_ut.cpp \
    adl_firewall_0_ut.cpp adl_firewall_1_ut.cpp adl_firewall_2_ut.cpp \
    func_type_ut.cpp etc_ut.cpp constexpr_if_ut.cpp variant_ut.cpp \ nstd_seq_ut.cpp \
    nstd_static_string_ut.cpp nstd_static_string_num_ut.cpp nstd_exception_ut.cpp \
    fixed_point_ut.cpp rational_ut.cpp nstd_static_string_path_ut.cpp

OBJDIR:= obj17/
CPP_VER = c++17
SHARED:=../../
include $(SHARED)make/env.mk
include $(SHARED)make/example.mk
include $(SHARED)make/gtest.mk
