@startditaa
ステップ1
    +---------------+       +---------------+ 
    |               |       |               | 
    |      str0     |       |      str1     | 
    |               |       |               | 
    +-------+-------+       +-------+-------+    
            |                       |
            V                       V
            nullptr                +------+        
                       move        |"hehe"|
                        +--------- | cGRE |
                        |          +------+
-=--------------------- | -=---------------------
ステップ2                   |
    +---------------+   |   +---------------+ 
    |               |   |   |               | 
    |      str0     |   |   |      str1     | 
    |               |   |   |           cRED| 
    +-------+-------+   |   +-------+-------+    
            |           |           |
            V           |           V
           +------+     |           nullptr
           |"hehe"|<----+
           | cGRE |
           +------+
@endditaa

