@startditaa
ステップ1
    +---------------+       +---------------+ 
    |               |       |               | 
    |      str0     |       | std꞉꞉string() | 
    |               |       |               | 
    +-------+-------+       +-------+-------+    
            |                       |
            V                       V
            nullptr                +------+        
                       move        |"hehe"|
                        +--------- | cGRE |
                        |          +------+
-=--------------------- | -=---------------------
ステップ2                   |
    +---------------+   |   +---------------+ 
    |               |   |   |               | 
    |      str0     |   |   | std꞉꞉string() | 
    |               |   |   |           cRED| 
    +-------+-------+   |   +-------+-------+    
            |           |           |
            V           |           V
           +------+     |           nullptr
           |"hehe"|<----+
           | cGRE |
           +------+
-=-----------------------------------------------
ステップ3
    +---------------+       +-=-------------+ 
    |               |       |               | destructing
    |      str0     |       | std꞉꞉string() | 
    |               |       |           cRED| 
    +-------+-------+       +-------+-------+    
            |                       |
            V                       V
           +------+                 nullptr
           |"hehe"|      
           | cGRE |
           +------+
@endditaa
