@startditaa
         スコープアウトした 
  +--->+-=----+
  |    |  x0  | y_꞉꞉use_count꞉1
  |    +---+--+
  |    |   |
  |    |   V
  |    |   Xオブジェクト 
  |    |
  |    V  スコープアウトした
  +----+-=----+ 
       |  y0  | x_꞉꞉use_count꞉1
       +--+---+
          |
          V
          Yオブジェクト

@endditaa



