VPATH=../template_cpp17
SRCS17:= exists_func_ut.cpp safe_index_put_to_ut.cpp safe_vector_ut.cpp \
         nstd_type_traits_ut.cpp is_same_ut.cpp
SRCS:=\
    nstd_type2str_ut.cpp logger_0.cpp logger_0_ut.cpp logger_0_std_ut.cpp \
    logger_0_global_ut.cpp logger_0_logging_ut.cpp  logger_0_struct_ut.cpp \
    logger_0_no_put_to_ut.cpp nstd_0_ut.cpp is_void_ut.cpp \
    value_type_ut.cpp nstd_put_to_ut.cpp logger_ut.cpp nstd_static_string_num_ut.cpp \
    nstd_concepts_ut.cpp cplusplus.cpp \

SRCS+=$(SRCS17)

SHARED:=../../
include $(SHARED)make/env.mk
include $(SHARED)make/example.mk
include $(SHARED)make/gtest.mk
