VPATH=../template_cpp17
SRCS:= exists_func_ut.cpp safe_index_put_to_ut.cpp safe_vector_ut.cpp  nstd_type_traits_ut.cpp \
       is_same_ut.cpp 

OBJDIR:= obj20/
CPP_VER = c++20
SHARED:=../../
include $(SHARED)make/env.mk
include $(SHARED)make/example.mk
include $(SHARED)make/gtest.mk

