SRCS:=\
    accessor_ut.cpp active_object_ut.cpp bare_server.cpp bare_server_wrapper.cpp class_ut.cpp clone_ut.cpp \
    copy_and_swap_ut.cpp crtp_ut.cpp di_ut.cpp enum_operator_ut.cpp factory_shipping_lib.cpp factory_shipping_ut.cpp \
    find_files_old_style.cpp find_files_strategy.cpp find_files_ut.cpp future_ut.cpp guard_ut.cpp light_pimpl_ut.cpp \
    no_copy_and_swap_ut.cpp null_object_ut.cpp nvi_ut.cpp observer_ng.cpp observer_ok.cpp observer_ut.cpp \
    proxy_ut.cpp raii_ut.cpp singleton_ut.cpp state_machine_new.cpp state_machine_old.cpp state_machine_ut.cpp \
    strategy_shipping_ut.cpp string_holder_new.cpp string_holder_old.cpp string_holder_ut.cpp subject_ng.cpp \
    subject_ok.cpp template_method.cpp template_method_factory_ut.cpp template_method_ut.cpp visitor.cpp \
	stringize_ut.cpp visitor_crtp_ut.cpp visitor_ut.cpp widget_ng.cpp widget_ng_ut.cpp widget_ok.cpp widget_ok_ut.cpp \
    wrapped_server.cpp wrapped_server_proxy.cpp \

CPP_VER:= c++17
SHARED:=../../essential/
include $(SHARED)make/env.mk
include $(SHARED)make/example.mk
include $(SHARED)make/gtest.mk
